Repository ppc64le-cloud/test-infra, pull requests merged in 2020-10, with the labels that each got.

#72 Adding a job postsubmit-os-kubernetes-build-golang-master-ppc64le
  config/jobs/ppc64le-cloud/builds/openshift-kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/M

#73 cleanup job
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, size/M

#74 Remove network cleanup
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, size/XS

#76 Use TF13 and no need for setting up plugins
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, do-not-merge/invalid-commit-message, lgtm, size/S

#77 retry flake tests
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#79 Run only on master branch
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/XS

#81 Prow version bump to v20201020-a5b49bc903
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prow-controller-manager_rbac.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
Labels: approved, size/S

#82 Update pod utilities
  config/prow/config.yaml
  images/pod-utilities/Makefile
Labels: approved, size/S

#83 Add config and crier spec related changes for implementing slack reporter
  config/prow/cluster/crier_deployment.yaml
  config/prow/config.yaml
Labels: approved, lgtm, size/S

#85 test_verbose_timeout_warnings for bazel test
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#86 Run conformance every 3hrs
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS
