Repository ppc64le-cloud/test-infra, pull requests merged in 2020-12, with the labels that each got.

#93 Adding Prow job for k8s conformance tests with containerd runtime
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, lgtm, size/M

#92 Restrict TF to v0.13.5
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, lgtm, size/XS

#95 Adopt new centos 8.3 image for all the testing
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/XS

#96 Add break-kubetest-on-upfail flag to k8s conformance tests
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/XS

#97 Upgrade the pvsadm version in periodic cleanup job
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, lgtm, size/XS

#98 Increase TIMEOUT value to 600s for k8s UT using master golang
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/XS

#99 Extend the cleanup window to 48hrs
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, size/XS

#100 Adding k8s-build-version as metadata information to finished.json
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, lgtm, size/XS

#101 update the domain to prow.ppc64le-cloud.org
  config/prow/cluster/prow_ingress.yaml
  config/prow/config.yaml
Labels: approved, size/S
