Repository ppc64le-cloud/test-infra, pull requests merged in 2020-09, with the labels that each got.

#45 Run unit tests every 3hrs
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#46 Remove invalidcommitmsg check
  config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#49 Validate on TF 0.13 for PowerVM and PowerVS
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, do-not-merge/invalid-commit-message, lgtm, size/S

#50 Use full path instead of previous command argument
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, lgtm, size/XS

#51 Add build-bot yamls
  config/prow/build-bot/build-bot.yaml
  config/prow/build-bot/build-bot_service.yaml
Labels: approved, size/M

#52 Add a periodic job for building master golang
  config/jobs/periodic/golang/build-golang-periodics.yaml
Labels: approved, size/S

#53 Add k8s cross build for golang master
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/M

#54 Restrict the branch to master
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/XS

#55 Pick latest ci/latest build
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#56 Run golang periodics only if there is change from last build
  config/jobs/periodic/golang/build-golang-periodics.yaml
Labels: approved, size/S

#57 Use e2e test binary from the CI bucket
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#58 all-in-one image
  images/all-in-one/Dockerfile
  images/all-in-one/README.md
  images/all-in-one/version.txt
Labels: approved, size/L

#59 Push k8s artifacts post build
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/S

#60 Use a new all-in-one image for k8s tests
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M

#61 Target conformance to run in the k8s-ppc64le-cluster cluster
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#62 Remove host entry
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#63 Remove test-args
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#64 Install kubectl as a prereq
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/S

#65 Fix the kubectl permission
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#66 Add a job for 4.5 branch
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, lgtm, size/S

#67 Ignore the destroy errors if any
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#68 Add release-4.5 branch config for powervm
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
Labels: approved, lgtm, size/S

#70 Fix tide config for powervm repo
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: approved, size/S

#71 Change the instance to sydney
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS
