Repository ppc64le-cloud/test-infra, pull requests merged in 2020-08, with the labels that each got.

#26 Change health job to run once in 6hrs
  config/jobs/ppc64le-cloud/test-infra/test-infra-periodics.yaml
Labels: approved, size/XS

#27 Make ibm-cloud image more generic
  images/ibm-cloud/Dockerfile
  images/ibm-cloud/README.md
  images/ibm-cloud/requirements.txt
Labels: approved, lgtm, size/S

#28 Add TF code for IKS cluster created for Prow
  infra/clusters/modules/iks-cluster/main.tf
  infra/clusters/modules/iks-cluster/outputs.tf
  infra/clusters/modules/iks-cluster/provider.tf
  infra/clusters/modules/iks-cluster/variables.tf
  infra/clusters/modules/iks-cluster/versions.tf
  infra/clusters/projects/k8s-prow/00-provider.tf
  infra/clusters/projects/k8s-prow/README.md
  infra/clusters/projects/k8s-prow/main.tf
  infra/clusters/projects/k8s-prow/terraform.tfvars
  infra/clusters/projects/k8s-prow/variables.tf
Labels: approved, size/L

#29 Work with Terraform 0.12 at present
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, lgtm, size/XS

#32 Add ocp-power-automation/ocp4-upi-powervm
  config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#33 Add job for ocp-power-automation/ocp4-upi-powervm
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
Labels: approved, lgtm, size/S

#38 Job for the k8s conformance test
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M

#39 Remove ibm terraform provider download
  config/jobs/ppc64le-cloud/kubetest2-plugins/kubetest2-plugins-presubmit.yaml
Labels: approved

#40 Revert "Remove ibm terraform provider download"
  config/jobs/ppc64le-cloud/kubetest2-plugins/kubetest2-plugins-presubmit.yaml
Labels: approved, size/XS

#41 Remove network while deploying
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#42 Make cluster unique
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#43 Run every hour
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS

#44 Restrict the run to single node
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/XS
