Repository ppc64le-cloud/test-infra, pull requests merged in 2021-09, with the labels that each got.

#225 Update version to trigger build and push of pod-utility images
  images/pod-utilities/version.txt
Labels: size/XS, approved, lgtm

#226 Correct update-github-pages-submodule postsubmit job
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
Labels: size/XS, approved, lgtm

#228 Enable censoring-of-secret-data in prow setup
  config/prow/config.yaml
Labels: size/XS, approved, lgtm

#230 Presubmit Job for etcd repo
  config/jobs/etcd-io/etcd/etcd-presubmit.yaml
  config/prow/plugins.yaml
Labels: approved, size/M, lgtm

#231 Hook Service spec for Hook App with github app and Permissions screenshot
  config/prow/cluster/hook2_service.yaml
  screenshots/PowerCloudCI App Permissions.png
Labels: approved, size/S, lgtm

#235 Adding Storage Job
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Labels: approved, size/M, lgtm

#236 Adding ocp-power-automation/ocp4-playbooks to plugins
  config/prow/plugins.yaml
Labels: size/XS, approved, lgtm
