Repository ppc64le-cloud/test-infra, pull requests merged in 2021-01, with the labels that each got.

#102 Update bazel version to 3.4.1
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  images/bazel/Makefile
Labels: approved, lgtm, size/XS

#103 Add gcs credentials to the crier Deployment
  config/prow/cluster/crier_deployment.yaml
Labels: approved, lgtm, size/XS

#104 PR job for varify-all the pvsadm repo
  config/jobs/ppc64le-cloud/pvsadm/pvsadm-presubmit.yaml
Labels: approved, lgtm, size/S

#105 Cleanup every 4hrs
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, lgtm, size/XS

#106 Adding a periodic job to move logs from GCS to IBM s3
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Labels: approved, lgtm, size/M

#108 Adopt the upstream k8s ingress controller
  config/prow/cluster/prow_ingress.yaml
Labels: approved, size/XS

#109 Add comment
  config/jobs/ppc64le-cloud/pvsadm/pvsadm-presubmit.yaml
Labels: approved, size/XS

#110 Update GCS credential name
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, lgtm, size/S

#111 Fixing 141 error - SIGPIPE caused by head command in prow job `periodic-gcs-logs-cleanup`
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Labels: approved, lgtm, size/XS

#113 Update docs
  Deployment Guide.md
  config/prow/README.md
  config/prow/buildfarms/README.md
  config/prow/buildfarms/build-img_rbac.yaml
  hack/update-job-config.sh
Labels: approved, size/L

#114 Modify gcs-logs-cleanup job to decide no of rows based on jobname
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Labels: approved, lgtm, size/S

#107 buildbot-postsubmit-job
  config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml
Labels: approved, lgtm, size/M

#121 Modified pod-utilities Dockerfile and version in Makefile
  images/pod-utilities/Dockerfile
  images/pod-utilities/Makefile
Labels: approved, lgtm, size/S
