Repository ppc64le-cloud/test-infra, pull requests merged in 2021-08, with the labels that each got.

#213 update the centos image
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/XS

#214 Flip to prow-testbed-lon04 powervs instance
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/S

#215 Fix region and zone name
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved

#216 Enable the cleanup
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: size/XS, approved

#218 Update cerberus specs as per the bug fix in cerberus upstream
  config/prow/cluster/cerberus_configmaps.yaml
  config/prow/cluster/cerberus_deployment.yaml
Labels: approved, lgtm, size/XL

#222 Upgrade prow infra to version v20210830-fcbb70627f
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#223 Revert "Upgrade prow infra to version v20210830-fcbb70627f"
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#224 Upgrade prow infra on IKS cluster to v20210830-fcbb70627f
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm
