Repository ppc64le-cloud/test-infra, pull requests merged in 2021-11, with the labels that each got.

#253 Upgrade prow infra to v20211029-f2e5351ee3
  images/pod-utilities/version.txt
Labels: size/XS, approved, lgtm

#256 Update specs for upgrading prow cluster to v20211029-f2e5351ee3
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/XXL, lgtm

#259 Remove cluster-api-provider-powervs-imagebuild-job
  config/jobs/openshift/cluster-api-provider-powervs/cluster-api-provider-powervs-periodic.yaml
Labels: approved, size/M, lgtm

#260 Make monitoring prow as deployment
  config/prow/cluster/monitor-prow-controller_deployment.yaml
  config/prow/cluster/monitor-prow-controller_pod.yaml
Labels: approved, size/M, lgtm

#261 Make conformance tests run on a multinode cluster with no skip
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#262 Remove mapio periodic job
  config/jobs/periodic/machine-api-operator/build-machine-api-operator-image.yaml
Labels: approved, size/M, lgtm
