Repository ppc64le-cloud/test-infra, pull requests merged in 2021-06, with the labels that each got.

#192 Add job to build and push image for openshift-powervs/cluster-api-pro…
  config/jobs/openshift-powervs/cluster-api-provider-powervs/postsubmit.yaml
  config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#181 Updated config maps for grafana and influxdb
  config/prow/grafana-dashboard/grafana-dashboards_configmap.yaml
  config/prow/grafana-dashboard/grafana-dashboards_configmap_ocp4_powervs_e2e.yaml
  config/prow/grafana-dashboard/grafana-dashboards_configmap_ocp4_powervs_scale.yaml
  config/prow/grafana-dashboard/grafana_deployment.yaml
  config/prow/grafana-dashboard/grafana_ingress.yaml
  config/prow/grafana-dashboard/influxdb-script_configmap.yaml
  config/prow/grafana-dashboard/influxdb_deployment.yaml
  config/prow/grafana-dashboard/influxdb_pv.yaml
Labels: approved, lgtm, size/XXL

#193 Add job for building machine-api-operator image
  config/jobs/periodic/machine-api-operator/build-machine-api-operator-image.yaml
Labels: approved, lgtm, size/M

#194 Adding prow jobs for jenkins
  config/jobs/ppc64le-cloud/jenkins-infra/jenkins-infra-postsummit.yaml
  config/jobs/ppc64le-cloud/jenkins-infra/jenkins-infra-presummit.yaml
Labels: approved, lgtm, size/M

#197 Test if repo allows access for Prow job trigger
  config/jobs/Rajalakshmi-Girish/test/test-prow-trigger.yaml
  config/prow/plugins.yaml
Labels: approved, lgtm, size/M

#199 Adding namespace metadata to perfdash-deployment template
  config/prow/perfdash/perfdash-deployment.yaml
Labels: approved, lgtm, size/XS

#198 Adding node-throughput prow job config
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, lgtm, size/M

#200 Change Presubmit job for Prow Trigger to a new org
  config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml
  config/prow/plugins.yaml
Labels: approved, lgtm, size/S

#201 Auto assign the PRs for review
  config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#202 Fix image build job for cluster-api-provider-powervs
  config/jobs/openshift-powervs/cluster-api-provider-powervs/postsubmit.yaml
  config/jobs/openshift/cluster-api-provider-powervs/cluster-api-provider-powervs-periodic.yaml
Labels: approved, lgtm, size/L

#203 Upgrade Prow pod-utilities on IKS to v20210623-0c619adcf3
  images/pod-utilities/version.txt
Labels: approved, lgtm, size/XS

#205 Change pull-test-infra-prow-checkconfig job image v20210623-0c619adcf3
  config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml
Labels: approved, lgtm, size/XS

#204 Changes to Prow specs for upgrading to v20210623-0c619adcf3
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_rbac.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_rbac.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_rbac.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/horologium_rbac.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prow-controller-manager_rbac.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/statusreconciler_rbac.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/cluster/tide_rbac.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#206 Add .gitignore file
  .gitignore
Labels: approved, lgtm, size/XS

#207 Add GOPATH/bin to PATH for etcd-postsubmit job
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
Labels: approved, lgtm, size/XS

#208 Job Update for prow job config and perfdash deployment for storage
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/prow/perfdash/perfdash-deployment.yaml
Labels: approved, lgtm, size/L
