Repository ppc64le-cloud/test-infra, pull requests merged in 2021-03, with the labels that each got.

#140 Cerberus pod/related configmaps specs to monitor Prow Controller Health
  config/prow/cluster/cerberus_configmaps.yaml
  config/prow/cluster/cerberus_deployment.yaml
  config/prow/cluster/cerberus_rbac.yaml
Labels: approved, lgtm, size/XL

#146 Sunset the bazel run in the prow CI
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, lgtm, size/M

#147 README for upgrading IKS Prow Cluster
  config/prow/UpdateProwREADME.md
Labels: approved, lgtm, size/M

#150 Upgrade prow cluster specs to latest community version
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, lgtm, size/S

#151 Remove clone_uri
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Labels: approved, lgtm, size/XS

#145 Adding prow job for ocp-power-automation/ocp-power-automation.github.io
  config/jobs/ocp-power-automation/ocp-power-automation.github.io/ocp-power-automation.github.io-postsubmits.yaml
  config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
  config/prow/plugins.yaml
  images/mkdocs/Dockerfile
  images/mkdocs/Makefile
  images/mkdocs/version.txt
Labels: approved, lgtm, size/L

#152 Adding README
  images/mkdocs/README.md
Labels: approved, lgtm, size/XS

#153 Add service account detail to mkdocs post-submit job container
  config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
Labels: approved, lgtm, size/XS

#155 Updating README
  images/mkdocs/README.md
Labels: approved, lgtm, size/XS

#154 Modifying cerberus specs to latest upstream
  config/prow/cluster/cerberus_configmaps.yaml
  config/prow/cluster/cerberus_deployment.yaml
Labels: approved, lgtm, size/XL

#157 Fix for current exception in cerberus deployment
  config/prow/cluster/cerberus_configmaps.yaml
  config/prow/cluster/cerberus_deployment.yaml
Labels: approved, lgtm, size/XL

#156 Add spec for cherry-picker endpoint deployment
  config/prow/cluster/cherrypick_deployment.yaml
Labels: approved, lgtm, size/M

#144 Add external plugin cherrypick
  config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#158 Enable the cleanup job in Prow
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, lgtm, size/XS

#159 Add issue_comment event to cherrypick plugin
  config/prow/plugins.yaml
Labels: approved, lgtm, size/XS

#160 perfdash manifest addition
  config/prow/perfdash/namespace.yaml
  config/prow/perfdash/perfdash-deployment.yaml
  config/prow/perfdash/perfdash-ingress.yaml
  config/prow/perfdash/perfdash-service.yaml
Labels: approved, lgtm, size/M

#161 Adding postsubmit job for ocp4-upi-powervm
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
Labels: approved, lgtm, size/M

#162 Adding postsubmit job for ocp4-upi-powervs, ocp-powervm-faq, etc
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
Labels: approved, lgtm, size/L

#163 Change to test image-builder kubeconfig on new ppc build cluster
  images/all-in-one/README.md
Labels: approved, lgtm, size/XS
