Repository ppc64le-cloud/test-infra, pull requests merged in 2021-02, with the labels that each got.

#122 Upgrade prow to version v20210126-f0baa5f3d9
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prow-controller-manager_rbac.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/sinker_rbac.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, lgtm, size/M

#123 Changing the pod-utilities image to use alpine distro for builder
  images/pod-utilities/Dockerfile
Labels: approved, lgtm, size/XS

#124 Change prow pod-utilities to build binaries statically
  images/pod-utilities/Dockerfile
Labels: approved, lgtm, size/XS

#126 Change dc to tok04 for k8s conformance jobs
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/S

#127 Changed the wrong image name for k8s conformance jobs
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/XS

#125 adding ibmcloud postsubmit job
  config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml
Labels: approved, lgtm, size/M

#128 Changing k8s cluster names deployed by conformance jobs
  config/jobs/CLUSTERCONFIGS.md
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, lgtm, size/S

#129 Escape the angle brackets in CLUSTERCONFIGS.md for proper cluster names
  config/jobs/CLUSTERCONFIGS.md
Labels: approved, lgtm, size/XS

#130 Replace kubernetes-release-dev with k8s-release-dev
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, lgtm, size/XS

#134 Installing latest version of kubectl
  images/all-in-one/Dockerfile
  images/all-in-one/version.txt
Labels: approved, lgtm, size/XS

#137 Disable periodic-powervs-cleanup job to debug VM deployment failure
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: approved, lgtm, size/XS

#136 Adding file containing Bazel Versions
  images/bazel/Makefile
  images/bazel/version.txt
Labels: approved, lgtm, size/XS

#132 adding postsubmit bazel job
  config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
Labels: approved, lgtm, size/M

#139 Adding file containing pod-utilities version
  images/pod-utilities/Makefile
  images/pod-utilities/version.txt
Labels: approved, lgtm, size/XS

#135 Adding postsubmit pod-utilities job
  config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
Labels: approved, lgtm, size/M

#141 adding all-in-one postsubmit job
  config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
Labels: approved, lgtm, size/M

#131 Change of periodic-gcs-logs-cleanup to use googlecloudstorageclient instead of gsutil
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Labels: approved, lgtm, size/M
