Repository ppc64le-cloud/test-infra, pull requests merged in 2022-08, with the labels that each got.

#322 Upgrade Golang to fix master golang build failure
  config/jobs/periodic/golang/build-golang-periodics.yaml
Labels: size/XS, approved, lgtm

#325 Enhance CAPIBM E2E job
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test

#326 Add ocp 4.11 to the images list
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
Labels: size/XS, approved, lgtm

#327 Add ocp-power-automation/ocp4-playbooks-extras
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/plugins.yaml
Labels: size/XS, approved, lgtm

#329 update terraform version to latest for validate
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
Labels: approved, size/S, lgtm

#330 Change of s3 bucket names after migration to new account
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/S, lgtm

#331 Fix the presubmit job for the pvsadm project
  config/jobs/ppc64le-cloud/pvsadm/pvsadm-presubmit.yaml
Labels: approved, size/S, lgtm
