Repository ppc64le-cloud/test-infra, pull requests merged in 2022-05, with the labels that each got.

#308 Update ingress specs
  config/prow/cluster/cisearch_ingress.yaml
  config/prow/cluster/deck_ingress.yaml
  config/prow/cluster/hook_ingress.yaml
  config/prow/grafana-dashboard/grafana_ingress.yaml
  config/prow/perfdash/perfdash-ingress.yaml
Labels: approved, size/S, lgtm

#307 Change the secret used for secretstore_update for external secrets
  config/prow/external-secrets/README.md
  config/prow/external-secrets/public_cert.yaml
  config/prow/external-secrets/secretstore_update.yaml
Labels: approved, size/S, lgtm

#309 Upgrade Prow infra to v20220503-01ebd50188
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#311 Remove the workaround for kubetest2 issue #176
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#312 Add job for CAPIBM E2E using new janitor
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: approved, size/M, lgtm, ok-to-test
