Repository ppc64le-cloud/test-infra, pull requests merged in 2022-11, with the labels that each got.

#350 Upgrade prow to v20221102-f0b00eafb2
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#352 Presubmit job for gcs-cleaner repo
  config/jobs/ppc64le-cloud/gcs-cleaner/gcs-cleaner-presubmits.yaml
Labels: approved, size/S, lgtm

#351 Add presets for various jobs that use common volumes and env
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
  config/jobs/ocp-power-automation/ocp-power-automation.github.io/ocp-power-automation.github.io-postsubmits.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
  config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
  config/prow/config.yaml
Labels: approved, size/L, lgtm

#353 Update kubekins image to 1.25
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm
