Repository ppc64le-cloud/test-infra, pull requests merged in 2022-06, with the labels that each got.

#314 change service instance to syd05
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/S, lgtm

#315 Add mergeable prow external plugin
  config/prow/cluster/mergeable_deployment.yaml
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: approved, size/L, lgtm

#317 Remove the CAPIBM e2e job not using Boskos
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: approved, size/M, lgtm, ok-to-test

#319 Move prow jobs testbed and SM to new PCLOUD Upstream account
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/prow/external-secrets/public_cert.yaml
  config/prow/external-secrets/secretstore_update.yaml
Labels: approved, size/M, lgtm
