Repository ppc64le-cloud/test-infra, pull requests merged in 2022-02, with the labels that each got.

#278 Change the k8s cluster creation jobs to use centos-8-stream image
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#277 Introduce presets for capi-e2e job
  config/prow/config.yaml
Labels: approved, size/M, lgtm, ok-to-test

#279 Updated the pod-utilities image version to v20220201-d251d8b00d
  images/pod-utilities/version.txt
Labels: size/XS, approved, lgtm

#280 Add periodic job for capi-ibmcloud e2e test
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: approved, size/S, lgtm, ok-to-test

#281 Spec changes for upgrade prow infra to v20220201-d251d8b00d
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/deck_ingress.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/hook_ingress.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, lgtm, size/XL

#282 Change build.sh path in postsubmit-master-golang-etcd-build-test-ppc64le job
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
Labels: size/XS, approved, lgtm

#283 Set boskos host
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm, ok-to-test

#284 Adding Boskos deployments and configmaps
  config/prow/cluster/boskos.yaml
  config/prow/cluster/boskos_configmaps.yaml
  config/prow/cluster/boskos_janitor.yaml
  config/prow/cluster/boskos_reaper.yaml
Labels: approved, size/L, lgtm, ok-to-test
