Repository ppc64le-cloud/test-infra, pull requests merged in 2022-09, with the labels that each got.

#332 Correct the update-job-config.sh
  hack/update-job-config.sh
Labels: size/XS, approved, lgtm

#333 Change cerberus deployment to use stable image
  config/prow/cluster/cerberus_deployment.yaml
Labels: size/XS, approved, lgtm

#334 Use proper kubekins image
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm

#335 Update all-in-one image
  config/jobs/etcd-io/etcd/etcd-presubmit.yaml
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
  config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
  config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
  config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml
  config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
  config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
  config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml
  config/prow/cluster/monitor-prow-controller_deployment.yaml
Labels: approved, size/M, lgtm

#336 Optimize all-in-one image
  images/all-in-one/Dockerfile
  images/all-in-one/version.txt
Labels: approved, size/L, lgtm, tide/merge-method-squash

#338 Use go install instead of go get
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/S, lgtm

#337 Update all-in-one image 0.5
  config/jobs/etcd-io/etcd/etcd-presubmit.yaml
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
  config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
  config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
  config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml
  config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
  config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
  config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml
  config/prow/cluster/monitor-prow-controller_deployment.yaml
Labels: approved, size/M, lgtm

#339 Remove linkcheck binary from postsubmit-kubernetes-build-golang-master job
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#340 Reduce memory provisioned for the PowerVS instances deployed for storage-perf-tests
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#341 Update of prow specs to v20220926-17e1ece283
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/XXL, lgtm

#343 Fix the error with postsubmit-master-golang-kubernetes-conformance-test-ppc64le job
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#344 Display go version and env in go postsubmit jobs
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm
