Repository ppc64le-cloud/test-infra, pull requests merged in 2023-10, with the labels that each got.

#411 cleanup - remove raksh repository
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: approved, size/M, lgtm

#412 Upgrade prow infra to v20231004-f64f17f7bb
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#413 Use image SHA along with name as a good practice
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test

#414 Replace wget with cURL
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test

#415 Update golang to 1.20
  config/jobs/ppc64le-cloud/gcs-cleaner/gcs-cleaner-presubmits.yaml
Labels: size/XS, approved, lgtm

#416 Skip failing UT in postsubmit-master-golang-kubernetes-unit-test-ppc64le
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm
