Repository ppc64le-cloud/test-infra, pull requests merged in 2023-12, with the labels that each got.

#432 Remove ocp4-extra repo from mergeable plugin list
  config/prow/plugins.yaml
Labels: size/XS, approved, lgtm

#433 Add job yaml for running k8s e2e-node tests
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M, lgtm

#434 Amend the k8s e2e-node test job and add clusterconfig detail
  config/jobs/CLUSTERCONFIGS.md
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/S, lgtm

#430 Increase POD_STARTUP_LATENCY_THRESHOLD to 10s through test-overrides.
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Labels: approved, size/S, lgtm

#435 Update capi-ibmcloud jobs with new release v0.7.0
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: approved, size/S, lgtm

#436 Fix capi-ibmcloud vpc template for release branch 0.7.0
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm

#437 Fix to avoid failure with periodic-kubernetes-containerd-conformance-test-ppc64le
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#438 Remove ginko tester flags from k8s conformance job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm
