Repository ppc64le-cloud/test-infra, pull requests merged in 2023-11, with the labels that each got.

#420 Fix typo in the capibm job name
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm

#419 Upgrade prow infra to v20231101-86c2fe4d89
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#421 Add 4.14 and remove 4.10 release for new images
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
Labels: size/XS, approved, lgtm

#422 Add Approve and Mergeable plugins to ocp4-extra repo
  config/prow/plugins.yaml
Labels: size/XS, approved, lgtm

#424 Fix release-0.5 and release-0.6 vpc periodic jobs template names
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, lgtm

#425 Add PDeXchange org to prow plugins
  config/prow/plugins.yaml
Labels: approved, size/M, lgtm

#426 Add PDeXchange to tide config and cleanup extra approve configs
  config/prow/config.yaml
  config/prow/plugins.yaml
Labels: approved, size/S, lgtm

#427 Add manifest for build-img token secret
  config/prow/buildfarms/build-img_rbac.yaml
Labels: size/XS, approved, lgtm

#428 Use default_decoration_config_entries configuration
  config/prow/config.yaml
Labels: size/XS, approved, lgtm

#418 Add Kubeflow CI job to Prow
  config/jobs/periodic/kubeflow/kubeflow-pipelines-component.yaml
Labels: approved, size/S, lgtm, ok-to-test

#429 Add kubeflow kubeconfig and patch config
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm
