Repository ppc64le-cloud/test-infra, pull requests merged in 2023-08, with the labels that each got.

#399 Upgrade Prow infra to v20230801-2352e79673
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/prowjob_customresourcedefinition.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/XXL, lgtm

#398 Changes to update all-in-one image
  config/jobs/etcd-io/etcd/etcd-presubmit.yaml
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
  config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
  config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
  config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
  config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml
  config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
  config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
  config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml
  images/all-in-one/Dockerfile
  images/all-in-one/version.txt
Labels: approved, size/M, lgtm

#400 To prevent CI jobs from failing due to latest all-in-one:0.6
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#402 Remove openshift-tests run-upgrade dry-run command
  config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
Labels: size/XS, approved, lgtm

#401 8 vCPU limit
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#403 Update all-in-one image for master go k8s build job
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#404 Remove specs for runtime jobs to go to dedicated node
  config/jobs/periodic/containerd/test-containerd-periodics.yaml
  config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: approved, size/M, lgtm

#405 Add 4.13 and remove 4.9 release for new images
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
Labels: size/XS, approved, lgtm
