Repository ppc64le-cloud/test-infra, pull requests merged in 2024-05, with the labels that each got.

#464 Remove kubeflow-pipelines-component-yaml-ppc64le prowjob
  config/jobs/periodic/kubeflow/kubeflow-pipelines-component.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#465 Remove kubeflow build cluster config
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#466 Skip Failing Container Lifecycle test of k8s e2e_node suite
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#467 Start using centos-9-stream image for CI jobs
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/S, lgtm

#468 Add networks purge command to cleanup job
  config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Labels: size/XS, approved, lgtm

#469 Disable errexit before kubetest2 tf command
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/S, lgtm

#470 Add e2e jobs for CAPIBM release-0.8 branch and update kubekins-e2e images
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: approved, size/S, lgtm

#471 Update VPC job flavor for release-0.8
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: size/XS, approved, lgtm
