Repository ppc64le-cloud/test-infra, pull requests merged in 2024-06, with the labels that each got.

#472 Label Docker integration test CR YAMLs
  config/jobs/periodic/docker/periodic-ci-docker.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test

#474 Upgrade Prow Infra to v20240531-8e43f4d08
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#473 Update broken link to point to running prow jobs locally on kind.
  README.md
Labels: size/XS, approved, lgtm

#476 Update to latest avaiable versions in all-in-one image
  images/all-in-one/Dockerfile
  images/all-in-one/version.txt
Labels: approved, size/S, lgtm

#477 Bump all-in-one image to 0.7
  config/jobs/etcd-io/etcd/etcd-presubmit.yaml
  config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
  config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
  config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
  config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
  config/jobs/periodic/etcd/test-etcd-periodics.yaml
  config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
  config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
  config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
  config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
  config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml
  config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
  config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
  config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml
Labels: approved, size/M, lgtm

#479 Update ibmcloud commands
  config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test

#480 Containerd test version
  config/jobs/periodic/containerd/test-containerd-periodics.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test
