Repository ppc64le-cloud/test-infra, pull requests merged in 2024-12, with the labels that each got.

#508 remove verbose flag
  config/jobs/periodic/golang/build-golang-periodics.yaml
Labels: size/XS, approved, lgtm

#511 Change k8s UT Job name to suit testgrid
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#512 Install only required testers for corresponding jobs
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#514 Correct K8s Version path for 1-30 release job
  config/jobs/periodic/kubernetes/test-kubernetes-1.30-periodics.yaml
Labels: size/XS, approved, lgtm

#516 Update DinD ppc64le image to 0.11-ppc64le
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test

#515 Knative client main release job added
  config/jobs/periodic/knative/client/client-main.yaml
Labels: approved, size/M, lgtm

#518 Client 1.16 release job added, Cron timings modified
  config/jobs/periodic/knative/client/client-main.yaml
  config/jobs/periodic/knative/client/client-release-1.16.yaml
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Labels: approved, size/S, lgtm

#519 Update containerd periodic job to use 0.11-ppc64le DinD image
  config/jobs/periodic/containerd/test-containerd-periodics.yaml
Labels: approved, lgtm

#521 Update hypershift-powervs-cleanup job and include heterogenous CI
  config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
Labels: size/XS, approved, lgtm

#504 Knative Eventing - prow jobs to run upstream testing CI job
  config/jobs/periodic/knative/eventing/eventing-main.yaml
  config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml
Labels: approved, size/L, lgtm, ok-to-test
