Repository ppc64le-cloud/test-infra, pull requests merged in 2024-11, with the labels that each got.

#494 Integrate k8s-conformance job to use Boskos resources
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/prow/cluster/boskos.yaml
  config/prow/cluster/boskos_configmaps.yaml
  config/prow/cluster/boskos_janitor.yaml
  config/prow/cluster/boskos_reaper.yaml
  config/prow/external-secrets/external-secret-janitor.yaml
Labels: approved, size/L, lgtm

#497 Disable debug output while acquiring Boskos resource in k8s conformance job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#496 Upload content under _artifacts(cluster logs) to GCS
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#495 Add k8s artifacts building, push to COS for k8s conformance job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/prow/config.yaml
Labels: approved, size/M, lgtm

#486 Knative operator job added for ppc64le
  config/jobs/periodic/knative/operator/main/operator-main.gen.yaml
  config/prow/config.yaml
Labels: approved, size/L, lgtm, ok-to-test, tide/merge-method-squash

#498 Revert uploading of rundir artifacts to bucket
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#499 Change OS image of k8s cluster in conformance job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#500 Fix teardown issue for PowerVS VSIs on test failure
  config/jobs/periodic/knative/operator/main/operator-main.gen.yaml
Labels: approved, size/S, lgtm

#501 Knative operator 1.15 & 1.16 release jobs added
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.15.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Labels: approved, size/L, lgtm

#503 Change OS image for PowerVS jobs to CentOS Catalog Image
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: size/XS, approved, lgtm

#502 Remove cpu limit in periodic-kubernetes-containerd-conformance-test-ppc64le job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#505 Change k8s UT Job to run as non-root user on powervs
  config/jobs/CLUSTERCONFIGS.md
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M, lgtm

#507 Modify k8s conformance job to use new Secrest from SM
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/prow/config.yaml
  config/prow/external-secrets/cos-service-creds.yaml
  config/prow/external-secrets/iam-cred.yaml
  config/prow/external-secrets/secretstore-ibm-k8s-infra.yaml
  config/prow/external-secrets/ssh-private-key.yaml
Labels: approved, size/L, lgtm

#509 Update Boskos resources for k8s-conformance job
  config/prow/cluster/boskos_configmaps.yaml
Labels: size/XS, approved, lgtm
