Repository ppc64le-cloud/test-infra, pull requests merged in 2025-02, with the labels that each got.

#529 Modified cleanup logic for knative jobs
  config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-main.yaml
  config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-release-1.16.yaml
  config/jobs/periodic/knative/client/client-main.yaml
  config/jobs/periodic/knative/client/client-release-1.16.yaml
  config/jobs/periodic/knative/eventing/eventing-main.yaml
  config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Labels: approved, size/M, lgtm

#530 Modify RegEx to prevent deletion of resources created in local HyperShift clusters
  config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
Labels: size/XS, approved, lgtm

#531 Restrict INGRESS_CLASS env variable to required Knative jobs
  config/jobs/periodic/knative/client/client-main.yaml
  config/jobs/periodic/knative/client/client-release-1.16.yaml
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
  config/prow/config.yaml
Labels: approved, size/S, lgtm

#532 Added 1.17 release components for Knative
  config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-release-1.17.yaml
  config/jobs/periodic/knative/client/client-release-1.17.yaml
  config/jobs/periodic/knative/eventing/eventing-release-1.17.yaml
  config/jobs/periodic/knative/operator/operator-release-1.17.yaml
Labels: approved, size/M, lgtm

#533 kn-plugin-event component added on ppc64le
  config/jobs/periodic/knative-extensions/kn-plugin-event/kn-plugin-event-main.yaml
  config/jobs/periodic/knative-extensions/kn-plugin-event/kn-plugin-event-release-1.17.yaml
Labels: approved, size/L, lgtm

#535 Revert #430 as startup latency is <5s
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm
