Repository ppc64le-cloud/test-infra, pull requests merged in 2025-01, with the labels that each got.

#523 Cron job timings modified as per latest schedule
  config/jobs/periodic/knative/client/client-main.yaml
  config/jobs/periodic/knative/client/client-release-1.16.yaml
  config/jobs/periodic/knative/eventing/eventing-main.yaml
  config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Labels: approved, size/S, lgtm

#525 Code restructured
  config/jobs/periodic/knative/client/client-main.yaml
  config/jobs/periodic/knative/client/client-release-1.16.yaml
  config/jobs/periodic/knative/eventing/eventing-main.yaml
  config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Labels: approved, size/L, lgtm

#526 Rename repo name to knative-tkn-upstream-ci for Knative jobs
  config/jobs/periodic/knative/client/client-main.yaml
  config/jobs/periodic/knative/client/client-release-1.16.yaml
  config/jobs/periodic/knative/eventing/eventing-main.yaml
  config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml
  config/jobs/periodic/knative/operator/operator-main.yaml
  config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Labels: approved, size/S, lgtm

#524 0.12-ppc64le DinD image
  config/jobs/periodic/containerd/test-containerd-periodics.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: approved, size/S, lgtm, ok-to-test

#527 Update Hypershift Cleanup Job with new Heterogeneous workspace ID
  config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
Labels: size/XS, approved, lgtm

#528 Upgrade Prow Infra to v20241224-8e8a5cfe7
  config/prow/cluster/cherrypick_deployment.yaml
  config/prow/cluster/crier_deployment.yaml
  config/prow/cluster/crier_github_app_deployment.yaml
  config/prow/cluster/deck_deployment.yaml
  config/prow/cluster/ghproxy_deployment.yaml
  config/prow/cluster/hook_deployment.yaml
  config/prow/cluster/hook_github_app_deployment.yaml
  config/prow/cluster/horologium_deployment.yaml
  config/prow/cluster/prow-controller-manager_deployment.yaml
  config/prow/cluster/sinker_deployment.yaml
  config/prow/cluster/statusreconciler_deployment.yaml
  config/prow/cluster/tide_deployment.yaml
Labels: approved, size/S, lgtm

#522 Knative Eventing Kafka Broker - prow jobs to run upstream testing CI job
  config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-main.yaml
  config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-release-1.16.yaml
Labels: approved, size/L, lgtm, ok-to-test
