Repository ppc64le-cloud/test-infra, pull requests merged in 2025-03, with the labels that each got.

#534 Add CAPIBM job for release-0.10 and update the kubekins-e2e image
  config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Labels: approved, size/S, lgtm

#537 Remove ssh_key_secret from prow default config
  config/prow/config.yaml
Labels: size/XS, approved, lgtm

#538 Change image tag of k8s UT job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#539 Change branch from master to main for postsubmit-os-origin-build-golang-master-ppc64le job
  config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
Labels: size/XS, approved, lgtm

#542 Changes to gcr.io images
  README.md
  config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml
  config/prow/cluster/label_sync_cron_job.yaml
  config/prow/perfdash/perfdash-deployment.yaml
  hack/test-pj.sh
  images/pod-utilities/Makefile
  images/pod-utilities/README.md
Labels: approved, size/S, lgtm

#543 Change kubetest2-plugins repo to provider-ibmcloud-test-infra
  config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-1.30-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-1.31-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-1.32-periodics.yaml
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
  config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Labels: approved, size/M, lgtm

#544 Bump the golang for gcs-cleaner jobs
  config/jobs/ppc64le-cloud/gcs-cleaner/gcs-cleaner-presubmits.yaml
Labels: size/XS, approved, lgtm

#545 Refactor the boskos flow in periodic-kubernetes-containerd-conformance-test-ppc64le job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M, lgtm

#546 Remove unit tests
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M, lgtm

#547 Remove hack/boskos.sh related code from conformance job
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: approved, size/M, lgtm

#548 Add RESOURCE_TYPE and enable xtrace for kubetest2 command
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#549 Correct the RESOURCE_TYPE value assignment before boskos checkout
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm

#550 Fixes to periodic-kubernetes-containerd-conformance-test-ppc64le
  config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Labels: size/XS, approved, lgtm
