Repository ppc64le-cloud/test-infra, pull requests merged in 2025-07, with the labels that each got.

#562 Add additional_labels for pdexchange/pac repo
  config/prow/plugins.yaml
Labels: size/XS, approved, lgtm

#564 Priority label sync for PAC
  config/prow/cluster/label_sync_cron_job.yaml
Labels: size/XS, approved, lgtm

#566 Update the powervs workspace names in boskos configmap manifest
  config/prow/cluster/boskos_configmaps.yaml
Labels: approved, size/S, lgtm

#567 1.1-ppc64le DinD image
  config/jobs/periodic/containerd/test-containerd-periodics.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml
  config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test
